os:
  - linux
  - windows
language: node_js
sudo: true
node_js:
  - "10.12"
install:
  - npm i
  - npm run build
  - rm -rf ./node_modules
  - npm i --production
before_script:
  - npm i -g @angular/cli
  - set -e
  - cp -rf $(pwd) ~/ngw
  - cd ~
  - ng new test-project --skip-install --defaults=true
  - cd test-project
  - npm i
  - cp -rf "../ngw" "./node_modules/ngw"
  - npx create-symlink-cmd "./node_modules/ngw/bin/ngw" "./node_modules/.bin/ngw" "exec"
script:
  - "grep 'angular.*: \"' package-lock.json | sort -u"
  - ./node_modules/.bin/ngw --set-up
  - npm run build | fgrep ngw.config
