#!/usr/bin/env node
const intercept = require('@angular/cli/models/webpack-config');
intercept.NgCliWebpackConfig.prototype.buildConfigInner = intercept.NgCliWebpackConfig.prototype.buildConfig;
intercept.NgCliWebpackConfig.prototype.buildConfig = function() {
    const m = require('./webpack-transformer.config');
    const transformer = m && m.default || m;
    return transformer(config);
};

require.cache[require.resolve('@angular/cli/models/webpack-config')].NgCliWebpackConfig = intercept.NgCliWebpackConfig;

require('@angular/cli/bin/ng');
